enable: true
hide-players: false
disable-damage: true
disable-block-change: true
disable-move-inventory-items: true
first-join-message:
  - §cПриветствуем на сервере
  -      §cУдачной игры!
top:
  update-time: 30  #seconds
  population-holo:
    x: -82
    y: 38
    z: -2.5
  balance-holo:
    x: -76
    y: 38
    z: -7.5
no-log-for-commands:
  - /minecraft:me
  - /me
  - /tell
  - /msg
spawn:
  x: -82
  y: 40
  z: 13
  time-to-enable: 1800  #seconds
max-fly-height:
  enable: false
  value: 120
borders:
  map:
    x:
    z:
  city:
    x:
    z:
materials-value:
  iron_ore: 5
  iron_block: 5
  iron_ingot: 5
  gold_ore: 5
  gold_block: 5
  gold_ingot: 5
  diamond_ore: 5
  diamond_block: 5
  diamond: 5
  emerald_ore: 5
  emerald_block: 5
  emerald: 5