enable: true
hide-players: false
disable-damage: true
disable-block-change: true
top-update-time: 10  #seconds
spawn:
  x: -82
  y: 40
  z: 13
  time-to-enable: 1800  #seconds
max-fly-height:
  enable: false
  value: 120
borders:
  map:
    x:
    z:
  city:
    x:
    z:
materials-value:
  iron_ore: 5
  iron_block: 5
  iron_ingot: 5
  gold_ore: 5
  gold_block: 5
  gold_ingot: 5
  diamond_ore: 5
  diamond_block: 5
  diamond: 5
  emerald_ore: 5
  emerald_block: 5
  emerald: 5