name: BlockCityTycoonGlobal
version: '${project.version}'
main: me.darkmun.blockcitytycoonglobal.BlockCityTycoonGlobal
authors: [ Darkmun ]
depend: [ProtocolLib, PacketWrapper, Vault]
commands:
  bctglobal:
    description: Команда для релоада плагина (ну типо))
  showplayers:
    description: Показать игроков, которые сейчас на сервере
    aliases:
      - showp
      - sp
  hideplayers:
    description: Скрыть игроков, которые сейчас на сервере
    aliases:
      - hidep
      - hp
  top:
    description: Показывает топ-10 игроков по численности. С аргументом enable отображает топ в уровне игрока (обновляется каждые несколько секунд).
  sell:
    description: Для продажи блоков\слитков\гемов
  givebook:
    description: Выдача гайда
  spawn:
    description: Телепортация на спавн раз в 30 минут
  flight:
    description: Даёт/забирает у игрока возможность к полету
  speed:
    description: Увеличивает/уменьшает скорость игроку
  sellall:
    description: Даёт/забирает возможность продать сразу все ресурсы из инвентаря
  instantspawn:
    description: Даёт/забирает возможность мгновенного спавна
  automelting:
    description: Даёт/забирает возможность автопереплавки при вскапывании блоков